export const projects = [
  {
    title: 'Food ordering',
    description: "A full stack app that is used for ordering food. The front-end is written in next.js and the database is mongodb which it connects to by using the mongoose library. The application has a Slider with graphics designed in Adobe XD, manually adding products and paying with PayPal.",
      image: '/images/8.png',
      tags: ['Next.js', 'MongoDB', 'Redux', 'Rest API'],
    source: '',
    visit: 'https://github.com/Wojciech-Jezierski/Food-ordering',
    id: 1,
  },
  {
    title: 'Movie App',
    description: "An application that allows you to search for a movie by its title thanks to the API from the omdbapi.com website. The database includes a number of movies from different categories. The technology I used for this project is mainly React.",
    image: '/images/1.png',
    tags: ['JavaScript', 'React'],
    source: 'https://adoring-nobel-87a33c.netlify.app/',
    visit: 'https://github.com/Wojciech-Jezierski/Movie-app',
    id: 2,
  },
  {
    title: 'Expense Tracker',
    description: "Application for expense tracker build in plain JavaScript and React using hooks(UseState, useContext, useReducer) and the context API.",
    image: '/images/4.png',
    tags: ['React', 'API'],
    source: '',
    visit: 'https://github.com/Wojciech-Jezierski/Expense-tracker',
    id: 3,
  },
  {
    title: 'Weather App',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/3.png',
      tags: ['React', 'API'],
    source: 'https://friendly-ardinghelli-78c093.netlify.app/',
    visit: 'https://github.com/Wojciech-Jezierski/weather-app',
    id: 4,
  },
  {
    title: 'Clock',
    description: "Final project on study, which was created in JavaScript, HTML, CSS and canvas.",
      image: '/images/9.png',
      tags: ['HTML', 'CSS', 'JavaScript', 'Canvas'],
    source: 'https://tubular-figolla-46e50b.netlify.app/',
    visit: 'https://github.com/Wojciech-Jezierski/Clock',
    id: 5,
  },
  {
    title: 'E-Commerce store',
    description:"Online store made from scratch. Some products have their own description and additional pictures. Validation form is accessible in the account tab. Technologies used for this project are HTML, CSS and JavaScript.",
    image: '/images/2.png',
    tags: ['HTML', 'CSS', 'JavaScript', 'jQuery'],
    source: 'https://happy-wright-c7b999.netlify.app/',
    visit: 'https://github.com/Wojciech-Jezierski/E-commerce-website',
    id: 6,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started my Study on WSB Gdańsk', },
];